//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRA_Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EGGEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembler.
        /// </summary>
        internal static string Assembler {
            get {
                return ResourceManager.GetString("Assembler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession {
            get {
                return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmExitGame {
            get {
                return ResourceManager.GetString("ConfirmExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start the game,
        ///even though not all players are ready?.
        /// </summary>
        internal static string ConfirmForceStartGame {
            get {
                return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession {
            get {
                return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame {
            get {
                return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        internal static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected {
            get {
                return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in a suitable gamer profile
        ///in order to access this functionality.
        /// </summary>
        internal static string ErrorGamerPrivilege {
            get {
                return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession {
            get {
                return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while
        ///accessing the network.
        /// </summary>
        internal static string ErrorNetwork {
            get {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost {
            get {
                return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session is already full.
        /// </summary>
        internal static string ErrorSessionFull {
            get {
                return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found. It may have ended,
        ///or there may be no network connectivity
        ///between the local machine and session host.
        /// </summary>
        internal static string ErrorSessionNotFound {
            get {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait for the host to return to
        ///the lobby before you can join this session.
        /// </summary>
        internal static string ErrorSessionNotJoinable {
            get {
                return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Sessions.
        /// </summary>
        internal static string FindSessions {
            get {
                return ResourceManager.GetString("FindSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameMode :.
        /// </summary>
        internal static string GameMode {
            get {
                return ResourceManager.GetString("GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture The Flag.
        /// </summary>
        internal static string GameModeTypeCTF {
            get {
                return ResourceManager.GetString("GameModeTypeCTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathmatch.
        /// </summary>
        internal static string GameModeTypeDM {
            get {
                return ResourceManager.GetString("GameModeTypeDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Deathmatch.
        /// </summary>
        internal static string GameModeTypeTDM {
            get {
                return ResourceManager.GetString("GameModeTypeTDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (host).
        /// </summary>
        internal static string HostSuffix {
            get {
                return ResourceManager.GetString("HostSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Session.
        /// </summary>
        internal static string JoinSession {
            get {
                return ResourceManager.GetString("JoinSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Session.
        /// </summary>
        internal static string LeaveSession {
            get {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///A button, Space, Enter = ok
        ///B button, Esc = cancel.
        /// </summary>
        internal static string MessageBoxUsage {
            get {
                return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined.
        /// </summary>
        internal static string MessageGamerJoined {
            get {
                return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left.
        /// </summary>
        internal static string MessageGamerLeft {
            get {
                return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now the Host.
        /// </summary>
        internal static string MessageNewHost {
            get {
                return ResourceManager.GetString("MessageNewHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are now the Host.
        /// </summary>
        internal static string MessageYouAreHost {
            get {
                return ResourceManager.GetString("MessageYouAreHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiPlayer.
        /// </summary>
        internal static string Multiplayer {
            get {
                return ResourceManager.GetString("Multiplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplayer.
        /// </summary>
        internal static string MultiplayerMenu {
            get {
                return ResourceManager.GetString("MultiplayerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking....
        /// </summary>
        internal static string NetworkBusy {
            get {
                return ResourceManager.GetString("NetworkBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions found.
        /// </summary>
        internal static string NoSessionsFound {
            get {
                return ResourceManager.GetString("NoSessionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Bots.
        /// </summary>
        internal static string NumberOfBots {
            get {
                return ResourceManager.GetString("NumberOfBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string NumberOfBots10 {
            get {
                return ResourceManager.GetString("NumberOfBots10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string NumerOfBots20 {
            get {
                return ResourceManager.GetString("NumerOfBots20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        internal static string PlayerMatch {
            get {
                return ResourceManager.GetString("PlayerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby {
            get {
                return ResourceManager.GetString("ReturnToLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScoreToWin :.
        /// </summary>
        internal static string ScoreToWin {
            get {
                return ResourceManager.GetString("ScoreToWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ScoreToWinType1 {
            get {
                return ResourceManager.GetString("ScoreToWinType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string ScoreToWinType3 {
            get {
                return ResourceManager.GetString("ScoreToWinType3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ScoreToWinType5 {
            get {
                return ResourceManager.GetString("ScoreToWinType5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50.
        /// </summary>
        internal static string ScoreToWinTypeFifty {
            get {
                return ResourceManager.GetString("ScoreToWinTypeFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string ScoreToWinTypeTwentyFive {
            get {
                return ResourceManager.GetString("ScoreToWinTypeTwentyFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Sessions.
        /// </summary>
        internal static string SearchSessions {
            get {
                return ResourceManager.GetString("SearchSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionProperties - .
        /// </summary>
        internal static string SessionProperties {
            get {
                return ResourceManager.GetString("SessionProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Link.
        /// </summary>
        internal static string SystemLink {
            get {
                return ResourceManager.GetString("SystemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theatre.
        /// </summary>
        internal static string Theather {
            get {
                return ResourceManager.GetString("Theather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training.
        /// </summary>
        internal static string Training {
            get {
                return ResourceManager.GetString("Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons :.
        /// </summary>
        internal static string Weapons {
            get {
                return ResourceManager.GetString("Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy.
        /// </summary>
        internal static string WeaponsTypeHeavy {
            get {
                return ResourceManager.GetString("WeaponsTypeHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string WeaponsTypeLight {
            get {
                return ResourceManager.GetString("WeaponsTypeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string WeaponsTypeNormal {
            get {
                return ResourceManager.GetString("WeaponsTypeNormal", resourceCulture);
            }
        }
    }
}
